project_name: pomerium-datasource

release:
  prerelease: auto
  github:
    owner: pomerium
    name: datasource
  name_template: "v{{.Version}}"

env:
  - GO111MODULE=on
  - CGO_ENABLED=0

before:
  hooks:
    - go mod download

builds:
  - id: datasource
    main: ./cmd/pomerium-datasource
    binary: pomerium-datasource
    goarch:
      - amd64
      - arm
      - arm64
    goos:
      - linux
      - darwin
      - windows
      - freebsd
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: freebsd
        goarch: arm64
      - goos: freebsd
        goarch: arm

    ldflags:
      - -s -w
      - -X github.com/pomerium/datasource/internal/version.Version={{.Version}}
      - -X github.com/pomerium/datasource/internal/version.GitCommit={{.ShortCommit}}
      - -X github.com/pomerium/datasource/internal/version.BuildMeta={{.Timestamp}}
      - -X github.com/pomerium/datasource/internal/version.ProjectName={{.ProjectName}}
      - -X github.com/pomerium/datasource/internal/version.ProjectURL=https://wwww.pomerium.com

archives:
  - name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    id: datasource
    builds:
      - datasource
    files:
      - none*
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

snapshot:
  name_template: "{{ .Version }}+next+{{ .ShortCommit }}"

dockers:
  - image_templates:
      - "pomerium/datasource:amd64-{{ .Tag }}"
      - "docker.cloudsmith.io/pomerium/datasource/pomerium-datasource:{{ .Tag }}"

    dockerfile: Dockerfile.release
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--label=repository=http://github.com/pomerium/datasource"
      - "--label=homepage=http://www.pomerium.com"

  - goarch: arm64
    image_templates:
      - "pomerium/datasource:arm64v8-{{ .Tag }}"
    dockerfile: Dockerfile.release
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--label=repository=http://github.com/pomerium/datasource"
      - "--label=homepage=http://www.pomerium.com"

docker_manifests:
  - name_template: "pomerium/datasource:{{ .Tag }}"
    image_templates:
      - pomerium/datasource:arm64v8-{{ .Tag }}
      - pomerium/datasource:amd64-{{ .Tag }}
