name: Lint
permissions:
  contents: read
on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
        with:
          fetch-depth: 0

      - uses: actions/setup-go@268d8c0ca0432bb2cf416faae41297df9d262d7f
        with:
          go-version: 1.19.x
          cache: true

      - uses: golangci/golangci-lint-action@07db5389c99593f11ad7b44463c2d4233066a9b1
        with:
          version: v1.49
